/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 * @author Muhammad Alfarizi
 */
public class Homes extends javax.swing.JFrame {

    /**
     * Creates new form Homes
     */
    public Homes() {
        initComponents();
        kosongkanForm();
        tampilkanCmbKarbo();
        tampilkanCmbBuah();
        tampilkanCmbProtein();
        tampilkanCmbSayur();
        tampilkanCmbSusu();
    }
    
    public void tampilkanCmbKarbo(){
        cmbkarbo.setModel(new DefaultComboBoxModel(new karbohidrat().getAll().toArray()));
    }
    
    public void tampilkanCmbBuah(){
        cmbbuah.setModel(new DefaultComboBoxModel(new buah().getAll().toArray()));
    }
    
    public void tampilkanCmbProtein(){
        cmbprotein.setModel(new DefaultComboBoxModel(new protein().getAll().toArray()));
    }
    
    public void tampilkanCmbSayur(){
        cmbsayur.setModel(new DefaultComboBoxModel(new sayur().getAll().toArray()));
    }
    
    public void tampilkanCmbSusu(){
        cmbsusu.setModel(new DefaultComboBoxModel(new susu().getAll().toArray()));
    }
    
    public void kosongkanForm(){
        txtbuah.setText("0");
        txtkarbo.setText("0");
        txtprotein.setText("0");
        txtsayur.setText("0");
        txtsusu.setText("0");
    }
    
    
    public void Homes() {
        initComponents();
        kosongkanForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckarbo = new javax.swing.JTextField();
        cprotein = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hbuah = new javax.swing.JTextField();
        hsayur = new javax.swing.JTextField();
        txtbuah = new javax.swing.JTextField();
        hsusu = new javax.swing.JTextField();
        cmbprotein = new javax.swing.JComboBox<>();
        hkarbo = new javax.swing.JTextField();
        cmbbuah = new javax.swing.JComboBox<>();
        hprotein = new javax.swing.JTextField();
        txtsayur = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtsusu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbsayur = new javax.swing.JComboBox<>();
        txttotal = new javax.swing.JLabel();
        cmbsusu = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btncount = new javax.swing.JButton();
        cbuah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkarbo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprotein = new javax.swing.JTextField();
        cmbkarbo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        csayur = new javax.swing.JTextField();
        csusu = new javax.swing.JTextField();
        txtket = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ckarbo.setEditable(false);
        ckarbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ckarbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckarboActionPerformed(evt);
            }
        });
        jPanel1.add(ckarbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 62, -1));

        cprotein.setEditable(false);
        cprotein.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cprotein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cproteinActionPerformed(evt);
            }
        });
        jPanel1.add(cprotein, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 62, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("x");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("kalori");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("x");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("x");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("x");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("x");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        hbuah.setEditable(false);
        hbuah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(hbuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 62, -1));

        hsayur.setEditable(false);
        hsayur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(hsayur, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 62, -1));

        txtbuah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtbuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 62, -1));

        hsusu.setEditable(false);
        hsusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(hsusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 62, -1));

        cmbprotein.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbprotein.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbprotein, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 252, -1));

        hkarbo.setEditable(false);
        hkarbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hkarbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hkarboActionPerformed(evt);
            }
        });
        jPanel1.add(hkarbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 62, -1));

        cmbbuah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbbuah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbbuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 252, -1));

        hprotein.setEditable(false);
        hprotein.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hprotein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hproteinActionPerformed(evt);
            }
        });
        jPanel1.add(hprotein, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 62, -1));

        txtsayur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtsayur, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 62, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Hasil");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        txtsusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtsusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 62, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("--------------   +");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        cmbsayur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbsayur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbsayur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 252, -1));

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttotal.setText(" ");
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 141, -1));

        cmbsusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbsusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbsusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 252, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Total");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah / gram");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        btncount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        btncount.setText("count");
        btncount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncountActionPerformed(evt);
            }
        });
        jPanel1.add(btncount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        cbuah.setEditable(false);
        cbuah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(cbuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 62, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Karbohidrat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Protein");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Buah");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sayur");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtkarbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkarbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkarboActionPerformed(evt);
            }
        });
        jPanel1.add(txtkarbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 62, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Susu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        txtprotein.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprotein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproteinActionPerformed(evt);
            }
        });
        jPanel1.add(txtprotein, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 62, -1));

        cmbkarbo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbkarbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbkarbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkarboActionPerformed(evt);
            }
        });
        jPanel1.add(cmbkarbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 252, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/function.png"))); // NOI18N
        jLabel7.setText("Count Calories");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 16, -1, -1));

        csayur.setEditable(false);
        csayur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(csayur, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 62, -1));

        csusu.setEditable(false);
        csusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(csusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 62, -1));

        txtket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtket.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txtket, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 730, 30));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Menu");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/function.png"))); // NOI18N
        jLabel9.setText("Count Calories");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 347, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/injury.png"))); // NOI18N
        jLabel10.setText("Gejala");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 172, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/solution.png"))); // NOI18N
        jLabel19.setText("Penanganan");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 231, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manfaat.png"))); // NOI18N
        jLabel21.setText("Manfaat");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 290, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cc.jpg"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hproteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hproteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hproteinActionPerformed

    private void txtproteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproteinActionPerformed

    private void hkarboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hkarboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hkarboActionPerformed

    private void btncountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncountActionPerformed
        // TODO add your handling code here:
        karbohidrat kar = new karbohidrat();
        int kalkarbo = kar.getByNama(cmbkarbo.getSelectedItem().toString()).getKalori();
        kar.setCount(Integer.parseInt(txtkarbo.getText()));
        ckarbo.setText(Integer.toString(kalkarbo));
        hkarbo.setText(Integer.toString(kalkarbo * kar.getCount()));
        int k = Integer.parseInt(hkarbo.getText());

        protein pro = new protein();
        int kalprotein = pro.getByNama(cmbprotein.getSelectedItem().toString()).getKalori();
        pro.setCount(Integer.parseInt(txtprotein.getText()));
        cprotein.setText(Integer.toString(kalprotein));
        hprotein.setText(Integer.toString(kalprotein * pro.getCount()));
        int p = Integer.parseInt(hprotein.getText());

        buah bu = new buah();
        int kalbuah = bu.getByNama(cmbbuah.getSelectedItem().toString()).getKalori();
        bu.setCount(Integer.parseInt(txtbuah.getText()));
        cbuah.setText(Integer.toString(kalbuah));
        hbuah.setText(Integer.toString(kalbuah * bu.getCount()));
        int b = Integer.parseInt(hbuah.getText());

        sayur sa = new sayur();
        int kalsayur = sa.getByNama(cmbsayur.getSelectedItem().toString()).getKalori();
        sa.setCount(Integer.parseInt(txtsayur.getText()));
        csayur.setText(Integer.toString(kalsayur));
        hsayur.setText(Integer.toString(kalsayur * sa.getCount()));
        int s = Integer.parseInt(hsayur.getText());

        susu su = new susu();
        int kalsusu = su.getByNama(cmbsusu.getSelectedItem().toString()).getKalori();
        su.setCount(Integer.parseInt(txtsusu.getText()));
        csusu.setText(Integer.toString(kalsusu));
        hsusu.setText(Integer.toString(kalsusu * su.getCount()));
        int susu = Integer.parseInt(hsusu.getText());

        int hasil= k + p + b + s + susu;

        txttotal.setText(Integer.toString(hasil));
        if(hasil >2000){
            txtket.setText("Total Kalori Yang Anda Konsumsi Lebih Besar Dari jumlah rata rata ");
        }else if(hasil < 1000){
            txtket.setText("Total Kalori Yang Anda Konsumsi Sesuai Dari jumlah rata rata ");
        }else{
            txtket.setText("Total Kalori Yang Anda Konsumsi Kurang Dari jumlah rata rata ");
        }
    }//GEN-LAST:event_btncountActionPerformed

    private void ckarboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckarboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckarboActionPerformed

    private void txtkarboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkarboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkarboActionPerformed

    private void cmbkarboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkarboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkarboActionPerformed

    private void cproteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cproteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cproteinActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new Gejala().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        new Penanganan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new Manfaat().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new Homes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncount;
    private javax.swing.JTextField cbuah;
    private javax.swing.JTextField ckarbo;
    private javax.swing.JComboBox<String> cmbbuah;
    private javax.swing.JComboBox<String> cmbkarbo;
    private javax.swing.JComboBox<String> cmbprotein;
    private javax.swing.JComboBox<String> cmbsayur;
    private javax.swing.JComboBox<String> cmbsusu;
    private javax.swing.JTextField cprotein;
    private javax.swing.JTextField csayur;
    private javax.swing.JTextField csusu;
    private javax.swing.JTextField hbuah;
    private javax.swing.JTextField hkarbo;
    private javax.swing.JTextField hprotein;
    private javax.swing.JTextField hsayur;
    private javax.swing.JTextField hsusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtbuah;
    private javax.swing.JTextField txtkarbo;
    private javax.swing.JLabel txtket;
    private javax.swing.JTextField txtprotein;
    private javax.swing.JTextField txtsayur;
    private javax.swing.JTextField txtsusu;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
